---
title: "Homework 4 Plots"
author: "Laya Buchanan"

date: 2020-09-21
output: github_document
---


```{r message = FALSE, echo = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("ny_noaa")
```


The following code separates the data variable into month, day, and year variables, converts the minimum and maximum temperatures into a more reasonable class type (numeric), and changes the snow and temperature units into more intuitive units (precipitation and snow measurements are converted from mm to cm and temperature measurements into degrees Celsius).

```{r}
noaa_df = 
ny_noaa  %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(month = recode(month, `01` = "january", `02` = "february",  `03` = "march", `04` = "april", `05` = "may", `06` = "june", `07` = "july", `08` = "august", `09` = "september", `10` = "october", `11` = "november", `12` = "december")) %>% 
  mutate(
    tmin = as.numeric(tmin),
    tmax = as.numeric(tmax),
    prcp = prcp/100,
    tmin = tmin/10,
    tmax = tmax/10,
    snow = snow/10,
    snow = snow/10
  )
  

noaa_df %>%
  sample_n(2500) %>% 
  plot_ly(
    x = ~tmax, y = ~tmin, type = "scatter", mode = "markers", "alpha" = 0.5)

noaa_df %>% 
  filter(year == 1997:2001) %>%
  plot_ly(y = ~tmax, type = "box", colors = "viridis")

noaa_df %>% 
  filter(year == 1997:2001) %>%
  count(tmax) %>% 
  plot_ly(x = ~tmax, y = ~n, color = ~tmax, type = "bar", text = ~paste("Temp: ", tmax, "Count: ", n), colors = "viridis")

noaa_df %>%
  filter(!snow == 0) %>% 
  filter(year == 1997:2001) %>% 
  plot_ly(
    x = ~tmax, y = ~snow, type = "scatter", mode = "markers", 
    text = ~paste("Max Temp: ", tmax, "Year: ", year), color = ~month, "alpha" = 0.7, colors = "viridis")

```
